In [1]:
print("rishitha")


rishitha


In [1]:
import numpy as np


In [2]:
arr = np.array([1, 2, 3, 4, 5])


squared = arr ** 2


mean_val = np.mean(arr)
std_val = np.std(arr)

print("Original array:", arr)
print("Squared array:", squared)
print("Mean:", mean_val)
print("Standard Deviation:", std_val)

Original array: [1 2 3 4 5]
Squared array: [ 1  4  9 16 25]
Mean: 3.0
Standard Deviation: 1.4142135623730951


In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
result = np.dot(A, B)
print(result)

[[ 4  4]
 [10  8]]


In [4]:
rand_arr = np.random.rand(3, 3)  # 3x3 matrix of random floats
print(rand_arr)

[[0.72725351 0.70003487 0.92083554]
 [0.32794858 0.02077679 0.10630053]
 [0.07435243 0.02249932 0.83448869]]


In [5]:
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print(reshaped)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:

arr = np.array([10, 20, 30, 40, 50])
filtered = arr[arr > 25]
print(filtered)

[30 40 50]


In [7]:
arr = np.array([1, 2, 3])
result = arr + 5
print(result)

[6 7 8]


In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked = np.vstack((a, b))
print(stacked)

[[1 2 3]
 [4 5 6]]


In [9]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix.T)

[[1 3 5]
 [2 4 6]]


In [10]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_vals = np.unique(arr)
print(unique_vals)

[1 2 3 4 5]


In [11]:
matrix = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(matrix)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]
